---
title: "immunogenicity.Rmd"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(stringdist)
library(reshape2)
library(parallel)
library(EMCluster)
library(ggplot2)
library(pROC)
select = dplyr::select
```

```{r}
dt.imm = fread("immunogenicity.txt") %>% as.data.frame
dt.vdjdb = fread("rearr_model/VDJDB_fullP_rob_ageing.txt") %>% as.data.frame

length(unique(dt.imm$antigen.epitope))
```
```{r}
dt.immv = merge(dt.imm %>% select(antigen.epitope, immunogenicity) %>% unique %>% as.data.frame,
                dt.vdjdb %>% 
                  filter(mhc.class == "MHCI", species == "HomoSapiens") %>%
                  group_by(antigen.epitope) %>% mutate(epi.count = n()) %>%
                  filter(epi.count > 30) %>%
                  summarise(pGen = median(genP_1mism_rob)),
                all.x=T, all.y=T)
```

```{r}
dt.all.epi = dt.vdjdb %>% 
  filter(mhc.class == "MHCI", species == "HomoSapiens") %>%
  group_by(antigen.epitope) %>% mutate(epi.count = n()) %>%
  filter(epi.count > 30) %>% select(antigen.species, antigen.epitope, epi.count) %>%
  unique

cmv.epi = dt.all.epi %>%
  filter(antigen.species == "CMV") %>%
  .$antigen.epitope

ebv.epi = dt.all.epi %>%
  filter(antigen.species == "EBV") %>%
  .$antigen.epitope

infl.epi = dt.all.epi %>%
  filter(antigen.species == "InfluenzaA") %>%
  .$antigen.epitope
```

```{r}
dt.epi.prop = rbindlist(lapply(strsplit(unique(dt.immv$antigen.epitope), split = ""),
                             function(x) data.table(aa = x,
                                                    antigen.epitope = paste0(x, collapse = "")))) 

dt.epi.prop = dt.epi.prop %>% 
  merge(fread("kidera.txt") %>% mutate(len = 1) %>%
          melt, by = "aa", allow.cartesian = T) %>%
  group_by(antigen.epitope, variable) %>%
  summarise(value = sum(value))
```
```{r}
dt.imm.prop = dt.immv %>%
  merge(dt.epi.prop) %>%
  dcast(antigen.epitope + immunogenicity + pGen ~ variable,
        value.var = "value")
```

### PCA analysis

```{r}
pc = prcomp(as.matrix(dt.imm.prop[,4:13]), 
            scale = T, rank = 2)
```

```{r}
dt.imm.prop$pc.x = pc$x[,1]
dt.imm.prop$pc.y = pc$x[,2]
```

```{r}
p20=ggplot(dt.imm.prop %>% filter(!is.na(immunogenicity)), aes(x = pc.x, y = pc.y)) +
  stat_density_2d(data = dt.imm.prop %>% select(pc.x, pc.y), geom = "raster",
                 aes(fill = ..density..), contour = F) +
  geom_density2d(aes(color = immunogenicity)) +
  scale_color_brewer("Immunogenicity", palette = "Set1") +
  scale_fill_gradient(low = "white", high="black") +
  scale_x_continuous(expand=c(0,0), limits = c(-4,4))+
  scale_y_continuous(expand=c(0,0), limits = c(-4,4))+
  theme_bw() + 
  theme(aspect = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p20
```

```{r}
p21 = ggplot(dt.imm.prop %>% filter(!is.na(immunogenicity) & immunogenicity == "Positive"), 
       aes(x = pc.x, y = pc.y)) +
  #stat_density_2d(data = dt.imm.prop %>% select(pc.x, pc.y), geom = "raster",
  #               aes(fill = ..density..), contour = F) +
  geom_density2d(aes(color = immunogenicity)) +
  geom_point(data=dt.imm.prop %>% filter(!is.na(pGen)), aes(size=pGen)) +
  scale_color_brewer("Immunogenicity", palette = "Set1") +
  scale_fill_gradient(low = "white", high="black") +
  scale_size_continuous("Rearrangement prob.") +
  scale_x_continuous(expand=c(0,0), limits = c(-4,4))+
  scale_y_continuous(expand=c(0,0), limits = c(-4,4))+
  theme_bw() + 
  theme(aspect = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p21
```

### Pure distances

```{r}
mm = as.matrix(dt.imm.prop[,4:13])
rownames(mm) = dt.imm.prop$antigen.epitope
vdjdb_epis = unique((dt.immv %>% filter(!is.na(pGen)))$antigen.epitope)
dd = dist(mm) %>% as.matrix %>% melt %>% 
  as.data.table %>% 
  filter(Var1 %in% vdjdb_epis | Var2 %in% vdjdb_epis)
```

```{r}
dd2 = dd
tmp = dd$Var1
dd2$Var1 = dd$Var2
dd2$Var2 = tmp
dd = rbind(dd, dd2) %>%
  filter(Var1 %in% vdjdb_epis & !(Var2 %in% vdjdb_epis))
```

```{r}
dt.imm.ann = as.data.table(dd) %>%
  merge(dt.immv %>% mutate(Var1 = antigen.epitope) %>% select(Var1, pGen), by = "Var1") %>%
  merge(dt.immv %>% mutate(Var2 = antigen.epitope) %>% select(Var2, immunogenicity), by = "Var2")

dt.imm.ann = dt.imm.ann %>%
  group_by(Var1, pGen) %>%
  summarise(tscore = t.test(value[which(immunogenicity == "Positive")],
                       value[which(immunogenicity == "Negative")], alternative = "less")$statistic)
```

```{r}
fancy_scientific = function(l) {
     # turn in to character string in scientific notation
     l = format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l = gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l = gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
}

p22=ggplot(dt.imm.ann, 
       aes(x = tscore, y = pGen)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_smooth(method = "lm", color = "red") +
  geom_point() +
  scale_y_log10("Rearrangement probability", labels = fancy_scientific) +
  scale_x_continuous("T-score (immunogenic vs non-immunogenic)") +
  theme_bw() +
  theme(aspect.ratio = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p22

summary(lm(log(pGen) ~ tscore, dt.imm.ann))

summary(lm(log(pGen) ~ tscore, dt.imm.ann %>% filter(!(Var1 %in% c(cmv.epi, ebv.epi, infl.epi)))))
```

## SVM-based P-values

```
library(e1071)
#Perform grid-based search to estimate optimal SVM parameters

#svm_params = expand.grid(C = 2^seq(-1,8,by=1),
#                         gamma = 2^seq(1,-6,by=-1))
svm_params = expand.grid(C = 2^seq(-1,8,by=1),
                         gamma = 0.25 * 2^seq(1,-6,by=-1))

svm_train_data = dt.imm.prop %>% filter(!is.na(immunogenicity)) %>%
                select(immunogenicity,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10)
svm_train_data$immunogenicity = as.factor(svm_train_data$immunogenicity)

pred_svm = function(params) {
  svm_mdl = svm(immunogenicity ~ ., 
              data= svm_train_data,
              cross = 3,# probability = T,
              cost = params$C, gamma = params$gamma, cachesize = 2000)
  #list(mdl = svm_mdl)
  list(C = params$C,
       gamma = params$gamma,
       acc = svm_mdl$tot.accuracy)
}

#grid_search_res = mclapply(apply(svm_params, 1, as.list),
#                           pred_svm, mc.cores = nrow(svm_params))

dt.grid_search_res = as.data.table(t(matrix(unlist(grid_search_res), nrow = 3)))
colnames(dt.grid_search_res) = c("C", "gamma", "acc")

ggplot(dt.grid_search_res, aes(x = C, y = gamma)) +
  geom_contour(aes(z = acc,colour = ..level..)) +
  scale_x_log10() +
  scale_y_log10() +
  theme_bw()

svm_mdl = svm(as.factor(immunogenicity) ~ ., 
              #kernel = "linear",
              cost = 1, gamma = 0.25,
              data=dt.imm.prop %>% filter(!is.na(immunogenicity)) %>%
                select(immunogenicity,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10),
              cross = 5, probability = T)

print(svm_mdl)
summary(svm_mdl)

#svm_mdl$tot.accuracy

dt.imm.ann.2 = dt.imm.prop %>% filter(!is.na(pGen))
dt.imm.ann.2$immunogenicity = NULL

svm_pred = predict(svm_mdl, 
                   newdata = dt.imm.ann.2,
                   probability = T)

dt.imm.ann.2$pImm = attr(svm_pred, "probabilities")[,2]

ggplot(dt.imm.ann.2, aes(x = pImm, y = pGen)) +
  geom_smooth(method = "lm", color = "red") +
  geom_point() +
  scale_y_log10("Rearrangement probability") +
  scale_x_continuous("T-score (immunogenic vs non-immunogenic).") +
  theme_bw() +
  theme(aspect.ratio = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())

summary(lm(log(pGen) ~ pImm, dt.imm.ann.2))
```

## EM-based classifier

```{r}
x.epi.prop = dt.imm.prop[,4:13]
lab.epi.prob = with(dt.imm.prop, ifelse(immunogenicity == "Positive", 1, 2))
lab.epi.prob = with(dt.imm.prop, ifelse(!is.na(pGen), 0, lab.epi.prob))
res_em = init.EM(as.matrix(x.epi.prop), nclass = 2, lab = lab.epi.prob)

res_probs = e.step(as.matrix(x.epi.prop), res_em, norm = F)
res_probs = exp(as.data.table(res_probs))
colnames(res_probs) = c("Gamma.unnorm.V1", "Gamma.unnorm.V2")

res_probs2 = e.step(as.matrix(x.epi.prop), res_em)
res_probs2 = as.data.table(res_probs2)
```

Classifier performance

```{r}
summary(res_em)
df.ctest = data.frame(immunogenicity = dt.imm.prop$immunogenicity) %>% cbind(res_probs2) %>% 
  filter(!is.na(immunogenicity)) 

p26x = df.ctest %>%
  ggplot(aes(x = Gamma.V1, fill = immunogenicity)) +
  geom_density(alpha = 0.9) +
  scale_fill_brewer("Immunogenic", palette = "Set1", labels = c("No", "Yes")) +
  scale_x_continuous("P(Immunogenic)") +
  scale_y_continuous("Density") +
  theme_bw() +
  theme(aspect = 1, 
        legend.position = "bottom",
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p26x

roc(immunogenicity ~ Gamma.V1, df.ctest, ci = F, plot = F)
-2*(3911 * log(0.5168) + 3671 * log(0.4832))
ggsave("figures/p26x.pdf", p26x)
```

```{r}
dt.imm.ann.3 = cbind(dt.imm.prop, res_probs, res_probs2) %>% 
  filter(!is.na(pGen))
```

```{r}
p23=ggplot(dt.imm.ann.3, aes(x = Gamma.V1, y = pGen)) +
  #geom_vline(xintercept = 0.5, linetype = "dashed") +
  geom_smooth(method = "lm", color = "red") +
  geom_point() +
  scale_y_log10("Rearrangement probability", labels = fancy_scientific) +
  scale_x_continuous("P(Immunogenic)") +
  theme_bw() +
  theme(aspect.ratio = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p23

summary(lm(log(pGen) ~ Gamma.V1, dt.imm.ann.3))

summary(lm(log(pGen) ~ Gamma.V1, dt.imm.ann.3 %>% filter(!(antigen.epitope %in% c(cmv.epi, ebv.epi, infl.epi)))))
```

```{r}
p24=ggplot(dt.imm.ann.3, aes(x = Gamma.unnorm.V1, y = pGen)) +
  geom_smooth(method = "lm", color = "red") +
  geom_point() +
  scale_y_log10("Rearrangement probability", labels = fancy_scientific) +
  scale_x_log10("D(Immunogenic)", labels = fancy_scientific) +
  theme_bw() +
  theme(aspect.ratio = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p24

summary(lm(log(pGen) ~ log(Gamma.unnorm.V1), dt.imm.ann.3))

summary(lm(log(pGen) ~ log(Gamma.unnorm.V1), dt.imm.ann.3 %>% filter(!(antigen.epitope %in% c(cmv.epi, ebv.epi, infl.epi)))))

dt.imm.ann.3 %>% filter(antigen.epitope %in% c(cmv.epi)) %>% print
```

## Predicting precursor frequency

```{r}
mdl_p = lm(log(pGen) ~ f1 + f2 + f3 + f4 + f5 + f6 + f7 + f8 + f9 + f10, #len + f6 + f10, 
           dt.imm.prop %>% filter(!is.na(pGen)))
summary(mdl_p)
```

```{r}
pred_p = predict(mdl_p, dt.imm.prop)
```

```{r}
dt.pred_p = dt.imm.prop
dt.pred_p$pGenPred = pred_p
```

```{r}
p25=ggplot(dt.pred_p %>% filter(!is.na(immunogenicity)), aes(x = exp(pGenPred),
                                                         color = immunogenicity)) +
  stat_ecdf() +
  ylab("CDF") +
  scale_x_log10("Predicted rearrangement probability", labels = fancy_scientific) +
  scale_color_brewer("Immunogenicity", palette = "Set1") +
  theme_bw() + 
  theme(aspect = 1,
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p25

ks.test((dt.pred_p %>% filter(!is.na(immunogenicity) & immunogenicity == "Positive"))$pGenPred,
        (dt.pred_p %>% filter(!is.na(immunogenicity) & immunogenicity == "Negative"))$pGenPred)
```

```{r}
ggsave("figures/p20.pdf", p20)
ggsave("figures/p21.pdf", p21)
ggsave("figures/p22.pdf", p22)
ggsave("figures/p23.pdf", p23)
ggsave("figures/p24.pdf", p24)
ggsave("figures/p25.pdf", p25)
```



