---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(VGAM)
require(vcd)
require(MASS)

select = dplyr::select
```

```{r}
dt.vdjdb = fread("vdjdb_dump/vdjdb.slim.txt") %>%
  filter(species == "HomoSapiens", gene == "TRB") %>%
  select(cdr3, 
         v.segm, j.segm,
         antigen.epitope, antigen.species,
         mhc.a, mhc.b, mhc.class)

dt.hip.annot = fread('zcat annotations/hip_annot_1.txt.gz')
dt.hip.stats = fread("annotations/hip_stats.txt")
```

Select good epitopes

```{r}
dt.vdjdb.epicount = dt.vdjdb %>%
  group_by(antigen.epitope) %>%
  summarise(total = n()) %>%
  arrange(-total)

print(dt.vdjdb.epicount)

good_epi = (dt.vdjdb.epicount %>% filter(total >= 30))$antigen.epitope
```

Total number of rearrangements in HIP

```{r}
HIP_R = with(dt.hip.stats, sum(diversity - nc_diversity))
```

Get full DB incl. TCRs that were not detected

```{r}
dt.hip.annot.full = dt.hip.annot %>%
  group_by(cdr3, 
         v.segm, j.segm,
         antigen.epitope, antigen.species,
         mhc.a, mhc.b, mhc.class) %>%
  summarise(incidence = sum(incidence), 
            convergence = sum(convergence), 
            occurrences = sum(occurrences)) %>%
  merge(dt.vdjdb, all.y = T, by = c("cdr3", 
         "v.segm", "j.segm",
         "antigen.epitope", "antigen.species",
         "mhc.a", "mhc.b", "mhc.class")) %>%
  mutate(incidence = ifelse(is.na(incidence), 0, incidence), 
         convergence = ifelse(is.na(convergence), 0, convergence), 
         occurrences = ifelse(is.na(occurrences), 0, occurrences),
         occur_freq = occurrences / HIP_R,
         occur_freq_adj = (occurrences + 0.5) / HIP_R)
```

```{r}
dt.hip.annot.s = dt.hip.annot.full %>%
  filter(antigen.epitope %in% good_epi) %>%
  group_by(antigen.epitope, antigen.species) %>%
  summarise(unique = n(), occurrences = sum(occurrences))

ggplot(dt.hip.annot.s, aes(x = unique, y = occurrences)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(dt.hip.annot.full, aes(x = nchar(cdr3), group = nchar(cdr3), y = occur_freq_adj)) +
  geom_violin() +
  scale_y_log10() +
  scale_x_continuous(breaks = 5:25)
```

```{r}
ggplot(dt.hip.annot.full %>%
         filter(antigen.epitope %in% good_epi) %>%
         group_by(antigen.epitope, antigen.species) %>%
         summarise(frac_found = sum(occurrences > 0),
                   occurrences_mean_tr = sum(occurrences) / sum(occurrences > 0))) +
  geom_point(stat="identity", aes(x = frac_found, y = occurrences_mean_tr, color = antigen.species)) +
  geom_vline(xintercept = 20) #+

  #geom_label(aes(x = frac_found, y = occurrences_mean_tr, color = antigen.species, 
  #               label = antigen.epitope), fill = NA)
```


```{r}
ggplot(dt.hip.annot.full, aes(x=occurrences+1)) +
  stat_ecdf()
```

```{r}
pareto.MLE <- function(X)
{
   n <- length(X)
   m <- min(X)
   a <- n/sum(log(X)-log(m))
   return( c(m,a) ) 
}

# example. 

set.seed(42)
res=pareto.MLE(dt.hip.annot.full$occur_freq_adj)

dt.pareto.tmp = data.table(occur_freq_adj = (0.5:max(dt.hip.annot.full$occurrences)) / HIP_R)
dt.pareto.tmp$CDF = with(dt.pareto.tmp, 1 - (res[1] / occur_freq_adj)^res[2])

ggplot() +
  stat_ecdf(data = dt.hip.annot.full, aes(x = occur_freq_adj)) +
  geom_line(data = dt.pareto.tmp, aes(x = occur_freq_adj, y = CDF), color = "red") +
  scale_x_log10()

res2 = fitdistr(dt.hip.annot.full$occur_freq, "exponential")

dt.exp.tmp = data.table(occur_freq = (0:max(dt.hip.annot.full$occurrences)) / HIP_R)
dt.exp.tmp$CDF = with(dt.exp.tmp, 1 - exp(-occur_freq * res2[1]$estimate))

ggplot() +
  stat_ecdf(data = dt.hip.annot.full, aes(x = occur_freq)) +
  geom_line(data = dt.exp.tmp, aes(x = occur_freq, y = CDF), color = "red") +
  scale_x_log10()
```

```{r}
ggplot(dt.hip.annot.full %>%
         filter(antigen.epitope %in% good_epi), aes(x=antigen.epitope, 
                                                    y=occur_freq_adj,
                                                    fill=antigen.species)) +
  geom_violin() + stat_summary(fun.y=median,
                               geom="point", shape=21, fill = "white", color="black") +
  scale_y_log10(breaks = 10^(-9:-4)) +
  coord_flip() +
  #scale_fill_discrete(guide = F) +
  scale_fill_brewer(palette = "Set3") +
  theme_bw()
```

```{r}
dt.hip.annot.full$epi.len = nchar(dt.hip.annot.full$antigen.epitope)

ggplot(dt.hip.annot.full %>%
         filter(antigen.epitope %in% good_epi, mhc.class == "MHCI"), 
       aes(x=epi.len, group = epi.len, y=occur_freq)) +
  geom_violin() + 
  stat_summary(fun.y=median, geom="point", shape=21, fill = "white", color = "black") +
  scale_y_log10(breaks = 10^(-9:-4)) +
  coord_flip() +
  #scale_fill_discrete(guide = F) +
  #scale_fill_brewer(guide = F, palette = "Set3") +
  theme_bw()
```

```{r}
kidera = t(data.frame(lapply(strsplit("A,-1.56,-1.67,-0.97,-0.27,-0.93,-0.78,-0.2,-0.08,0.21,-0.48;R,0.22,1.27,1.37,1.87,-1.7,0.46,0.92,-0.39,0.23,0.93;N,1.14,-0.07,-0.12,0.81,0.18,0.37,-0.09,1.23,1.1,-1.73;D,0.58,-0.22,-1.58,0.81,-0.92,0.15,-1.52,0.47,0.76,0.7;C,0.12,-0.89,0.45,-1.05,-0.71,2.41,1.52,-0.69,1.13,1.1;Q,-0.47,0.24,0.07,1.1,1.1,0.59,0.84,-0.71,-0.03,-2.33;E,-1.45,0.19,-1.61,1.17,-1.31,0.4,0.04,0.38,-0.35,-0.12;G,1.46,-1.96,-0.23,-0.16,0.1,-0.11,1.32,2.36,-1.66,0.46;H,-0.41,0.52,-0.28,0.28,1.61,1.01,-1.85,0.47,1.13,1.63;I,-0.73,-0.16,1.79,-0.77,-0.54,0.03,-0.83,0.51,0.66,-1.78;L,-1.04,0,-0.24,-1.1,-0.55,-2.05,0.96,-0.76,0.45,0.93;K,-0.34,0.82,-0.23,1.7,1.54,-1.62,1.15,-0.08,-0.48,0.6;M,-1.4,0.18,-0.42,-0.73,2,1.52,0.26,0.11,-1.27,0.27;F,-0.21,0.98,-0.36,-1.43,0.22,-0.81,0.67,1.1,1.71,-0.44;P,2.06,-0.33,-1.15,-0.75,0.88,-0.45,0.3,-2.3,0.74,-0.28;S,0.81,-1.08,0.16,0.42,-0.21,-0.43,-1.89,-1.15,-0.97,-0.23;T,0.26,-0.7,1.21,0.63,-0.1,0.21,0.24,-1.15,-0.56,0.19;W,0.3,2.1,-0.72,-1.57,-1.16,0.57,-0.48,-0.4,-2.3,-0.6;Y,1.38,1.48,0.8,-0.56,0,-0.68,-0.31,1.03,-0.05,0.53;V,-0.74,-0.71,2.04,-0.4,0.5,-0.81,-1.07,0.06,-0.46,0.65", ";")[[1]], function (x) { strsplit(x, ",")[[1]] } ))); kidera = data.frame(kidera[,1], apply(kidera[, 2:11], 2, as.numeric)); kidera[,1] = as.character(kidera[,1]); row.names(kidera) = kidera[,1]; names(kidera) = c("aa", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10")
kidera$Len = 1

dt.epi.kidera = rbindlist(lapply(strsplit(good_epi, ""), 
                                 function(x) data.frame(antigen.epitope = paste(x, collapse = ""), aa = x))) %>%
  merge(kidera) %>%
  group_by(antigen.epitope) %>%
  summarise(f1 = sum(f1),f2 = sum(f2),f3 = sum(f3),f4 = sum(f4),f5 = sum(f5),
            f6 = sum(f6),f7 = sum(f7),f8 = sum(f8),f9 = sum(f9),f10 = sum(f10),
            Len = sum(Len)) %>%
  as.data.table
```

```{r}
ggplot(dt.hip.annot.full %>%
         filter(antigen.epitope %in% good_epi, mhc.class == "MHCI") %>%
         merge(dt.epi.kidera), 
       aes(x=Len, y=f2, weight = occur_freq)) +
  geom_density2d() +
  scale_y_log10(breaks = 10^(-9:-4)) +
  #scale_fill_discrete(guide = F) +
  #scale_fill_brewer(guide = F, palette = "Set3") +
  theme_bw()
```